added buttons
wiktorrudzki/Frontend-projekt pull request #19
Opened 2022-12-03 20:04 UTC by A-Janowski

![image](https://user-images.githubusercontent.com/107277685/205459654-28d38f0f-9728-43de-ad7d-8473ea62f622.png)
utworzyłem klasy dla predefiniowanych buttonów zgodnie z poleceniem Kuby

2022-12-03 20:05 UTC, A-Janowski commented
Zrobiłem osobny pull request bo pracowałem teraz na lapku a nie na swoim pececie więc stworzyłem też i nowego brancha, na którym to robiłem

2022-12-03 20:38 UTC, JN0122 requested changes
Bardziej chodziło mi, żeby utworzyć 4 różne guziki i tylko w propsach zawartość przekazywać.

Jak masz podobne style do guzików możesz w css zrobić taki myk jak na ss.

Możesz pomyśleć też nad zmianą nazw tych komponentów, żeby były uniwersalniejsze. Staraj się korzytać z reguły _DRY (Don't Repeat Yourself)_.
#### _buttons.scss
<img width="334" alt="Screenshot 2022-12-03 at 21 30 13" src="https://user-images.githubusercontent.com/33033063/205460879-47d9e389-5b1b-490e-9cb2-51e1d8fe0672.png">

#### PrimaryButton.tsx
<img width="485" alt="Screenshot 2022-12-03 at 21 33 27" src="https://user-images.githubusercontent.com/33033063/205461028-95114b5b-ee29-4148-8d0e-2f6ab2d969c7.png">

2022-12-04 09:49 UTC, A-Janowski commented
![image](https://user-images.githubusercontent.com/107277685/205484281-78a28b9c-8e4d-48ed-bc4f-9e7b3c03753c.png)
Zrobiłem tym razem 4 predefiniowane guziki, które powinny pokryć wszystkie nam potrzebne buttony na stronce.

2022-12-04 11:31 UTC, JN0122 requested changes
Tak na ogół jest super, jedynie jedna uwaga. Jak poprawisz to już będziemy mergować :)

2022-12-04 11:31 UTC, JN0122 commented on POLMED/src/styles/components/_button.scss
> +    width: 12.5em;
Wszystko super, mam tylko jedną małą uwagę, wydaje mi się, że lepiej będzie dać tutaj _min-width_.

2022-12-04 11:31 UTC, JN0122 commented on POLMED/src/styles/components/_button.scss
> +    width: 16.125em;
Tak samo

2022-12-04 11:31 UTC, JN0122 commented on POLMED/src/styles/components/_button.scss
> +    width: 12.5em;
Tak samo

2022-12-04 11:31 UTC, JN0122 commented on POLMED/src/styles/components/_button.scss
> +    width: 8.5em;
I jeszcze tutaj

2022-12-04 11:51 UTC, wiktorrudzki requested changes
pomysł z klasami jest spoko, realizacja też jest w porządku, ale po co tworzyć 4 osobne komponenty funkcyjne, jeśli można stworzyć jeden i za pomocą props przekazywać
- kontent
- props, dzięki któremu będziemy nadawać buttonowi odpowiednią klasę - wówczas będziemy mieli jeden komponent i na podstawie przekazanego propsa będziemy mu dawać odpowiednią klasę w css.
Oprócz tego jest naprawdę dobrze :D

2022-12-04 11:51 UTC, wiktorrudzki commented on POLMED/src/components/buttons/PrimaryBtn/index.tsx
> +const PrimaryBtn = ({content}:Props) => {
tu

2022-12-04 11:51 UTC, wiktorrudzki commented on POLMED/src/components/buttons/SecondaryBtn/index.tsx
> +const SecondaryBtn = ({content}:Props) => {
tu

2022-12-04 11:51 UTC, wiktorrudzki commented on POLMED/src/components/buttons/TertiaryBtn/index.tsx
> +const TertiaryBtn = ({content}:Props) => {
tu

2022-12-04 11:51 UTC, wiktorrudzki commented on POLMED/src/components/buttons/WarningBtn/index.tsx
> +const WarningBtn = ({content}:Props) => {
tu

2022-12-04 12:32 UTC, A-Janowski commented
Zastosowałem się do waszych porad i dodałem poprawioną wersję :D

2022-12-04 12:51 UTC, JN0122 requested changes

2022-12-04 12:51 UTC, JN0122 commented on POLMED/src/components/button/index.tsx
> +    className: string;
Możesz w TypeScripcie z góry zakładać jaki będziesz mieć string, wyeliminuje to literówki.
![image](https://user-images.githubusercontent.com/33033063/205491238-3d381a64-9c15-4940-8b74-34a341ad49fd.png)

2022-12-04 12:51 UTC, JN0122 commented on POLMED/src/components/button/index.tsx
> +    return <button className={className}>{content}</button>;
Proponuje dodawać tylko klasy, które powyżej wyszczególniłem. Wiemy, że jest to przycisk więc możemy z góry ustawić klasę _btn_.
![image](https://user-images.githubusercontent.com/33033063/205491451-fc8b15be-d1d5-4ede-904a-2e2a086cde9b.png)

2022-12-04 17:47 UTC, wiktorrudzki requested changes

2022-12-04 17:47 UTC, wiktorrudzki commented on POLMED/src/components/button/index.tsx
> +    return <button className={`btn ${className}`}>{content}</button>;
proponuję zmienić trochę nazewnictwo tego propsa, gdyż słowo className oznacza już samo w sobie nadanie klasy, gdy ktoś będzie z zewnątrz patrzył na komponent rodzica może zastanawiać się czy className to jest juz klasa dla komponentu czy przekazywany props
osobiście proponuję nazwę type | btnType | buttonType

2022-12-04 17:49 UTC, wiktorrudzki requested changes

2022-12-04 17:49 UTC, wiktorrudzki commented on POLMED/src/styles/components/_button.scss
>      border-color: $color-warning;
style, które się powtarzają dla wszystkich buttonów wrzuć w jedną klasę .btn, którą kuba Ci kazał nadać w poprzednim review. Wówczas każdy button będzie miał z góry konkretne wspólne style, a te, które muszą być indywidualnie przypisywane będzie miał dodawane za pomocą propsa.

2022-12-04 18:19 UTC, wiktorrudzki approved these changes
mergujemy, jesli kuba nic nie znajdzie

2022-12-04 19:18 UTC, JN0122 commented
Jest git, wrzucę już na main'a

2022-12-04 19:20 UTC, JN0122 approved these changes

2022-12-04 19:20 UTC, merged