Input task
wiktorrudzki/Frontend-projekt pull request #20
Opened 2022-12-04 12:40 UTC by JN0122

Dodałem component input, skrypt dynamicznie sprawdza czy dane pole jest zgodne z wymaganiami przesłanymi w propsach.
![image](https://user-images.githubusercontent.com/33033063/205490895-c79b5182-0e8e-4388-ab5b-5e6c6a2ef289.png)
![image](https://user-images.githubusercontent.com/33033063/205490884-97d1e09d-7b67-4e6b-8b2c-6f855fb7d0cf.png)

2022-12-04 17:43 UTC, wiktorrudzki requested changes
skróć zapis renderowania gwiazdki oznaczjące pole obowiązkowe i komponencik elegancko zrobiony

2022-12-04 17:43 UTC, wiktorrudzki commented on POLMED/src/components/form/_input/index.tsx
> +        {required ? <span className="form-field--label__star">*</span> : ""}
zamiast używać shortcuta z  ? i : możesz użyć warunkowego renderowania za pomocą &&
przykład:
warunek && <span>tresc</span>
Wówczas span zostanie wygenerowany tylko gdy warunek jest true

2022-12-05 15:29 UTC, JN0122 commented
Załatwione

2022-12-05 23:49 UTC, wiktorrudzki approved these changes

2022-12-05 23:49 UTC, merged