Added a button component.
wiktorrudzki/Frontend-projekt pull request #7
Opened 2022-11-27 19:13 UTC by A-Janowski

2022-11-28 15:49 UTC, wiktorrudzki reviewed
następnym razem jak będziesz wrzucał pr to dodaj do niego ss tego jak button aktualnie się prezentuje na stronie - podobnie z innymi taskami w przyszłości

2022-11-28 15:49 UTC, wiktorrudzki commented on POLMED/package.json
> +    "node-sass": "^7.0.3",
z tego co sie orientuje, nie potrzebujemy zadnej dodatkowej paczki, aby korzystac z sassa

2022-11-28 15:49 UTC, wiktorrudzki commented on POLMED/src/components/button/index.tsx
> +export default Button;
plik ma mieć zawsze ostatnią linijkę pustą

2022-11-28 15:49 UTC, wiktorrudzki commented on POLMED/src/components/button/index.tsx
> +const Button = () => {
docelowo chcemy aby nasz komponent brał jakieś propsy, dzięki którym będziemy mogli manipulować jego contentem oraz kolorem lub tez szerokością

dodaj na ten moment propsy, które będą odpowiadać za kolor oraz kontent i na ich podstawie ustawiaj odpowiednio kolor i kontent - jak cos to pisz do mnie na priv

2022-11-28 15:49 UTC, wiktorrudzki commented on POLMED/src/components/button/style.scss
> +Button {
nie chcemy stylować po elemencie html, raczej lepiej będzie nadać elementowi klasę i po klasie się odwoływać

2022-11-28 15:49 UTC, wiktorrudzki commented on POLMED/src/components/button/style.scss
> +    color: #66cc99;
color i border będzie nadawany automatycznie przez propsy w zalezności od tego co nasz button bedzie mial robic

2022-11-28 15:49 UTC, wiktorrudzki commented on POLMED/src/components/button/style.scss
> +    border: none;
z tego co się orientuje nasz button będzie potrzebował border

2022-11-28 15:49 UTC, wiktorrudzki commented on POLMED/src/components/button/style.scss
> +}
koniec pliku - pusta linia

2022-11-28 17:03 UTC, wiktorrudzki reviewed
aktualizacja odnosnie stylow

2022-11-28 17:03 UTC, wiktorrudzki commented on POLMED/src/components/button/style.scss
> +    background-color: #66cc994d;
nie piszemy sami kolorow na sztywno - zamiast tego zaimportuj plik global-styles z katalogu styles wewnatrz src i wykorzystaj zmienne css'owe color: var(--{nazwa zmiennej})

2022-11-29 10:16 UTC, A-Janowski commented
![image](https://user-images.githubusercontent.com/107277685/204502296-812c17ce-476f-4f71-96d6-d39bc9fa9742.png)
obraz przykładowych buttonów

2022-12-02 16:36 UTC, JN0122 reviewed
Proponuję, żebyś zamiast przekazywał wszystkich styli w propsach utworzył klasy dla predefiniowanych guzików. Łatwiej będzie nad wszystkim zapanować :)

2022-12-02 16:36 UTC, JN0122 requested changes
Proponuję, żebyś zamiast przekazywał wszystkich styli w propsach utworzył klasy dla predefiniowanych guzików. Łatwiej będzie nad wszystkim zapanować :)

2022-12-02 17:19 UTC, wiktorrudzki reviewed
mysle, ze pomysl kuby jest jak najbardziej trafny

2022-12-02 17:19 UTC, wiktorrudzki commented on POLMED/src/components/button/index.tsx
> +interface Props {
zapisz jako type a nie jako interface

2022-12-02 17:19 UTC, wiktorrudzki commented on POLMED/src/components/button/index.tsx
> +  borderColor: string;
jedyne co potrzebujemy przekazywac jako props to borderColor, color i backgroundColor + content

2022-12-02 17:19 UTC, wiktorrudzki commented on POLMED/src/components/button/style.css
>  }/*# sourceMappingURL=style.css.map */
brak konca linii

2022-12-02 17:19 UTC, wiktorrudzki commented on POLMED/src/components/button/style.scss
>  }
brak końca linii

2022-12-02 17:19 UTC, wiktorrudzki commented on POLMED/src/components/button/style.scss
> +.ButtonClass {
nazwy klas zaczynamy z malych liter, a slowa oddzielamy "-"

2022-12-02 17:19 UTC, wiktorrudzki commented on POLMED/src/styles/global-styles.css
> +  --green: #66CC994D;
po co ten kolor nam jest obecnie?

2022-12-02 17:19 UTC, wiktorrudzki commented on POLMED/src/styles/global-styles.css
> +  --green: #66CC994D;
do uzyskania jaśniejszego użyj czegoś takiego jak lighten() lub darken(), mozesz sobie znalezc w necie jak tego uzyc na luzie

2022-12-02 17:19 UTC, wiktorrudzki commented on POLMED/src/components/button/style.scss
>      text-transform: uppercase;
do styli dodaj tez lekki bold na foncie i uzyj troche mniejszgo font-size w buttonie

2022-12-03 20:39 UTC, closed without merging